<?php

namespace Container6aQTPmn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OkC16QwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.okC16Qw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.okC16Qw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'teacherRepository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'teacherRepository' => 'App\\Repository\\TeacherRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
