<?php

namespace Container6aQTPmn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YAO3wGbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yAO3wGb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yAO3wGb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'groupRepository' => ['privates', 'App\\Repository\\GroupRepository', 'getGroupRepositoryService', true],
            'groupUserRepository' => ['privates', 'App\\Repository\\GroupUserRepository', 'getGroupUserRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'groupRepository' => 'App\\Repository\\GroupRepository',
            'groupUserRepository' => 'App\\Repository\\GroupUserRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
