<?php

namespace Container6aQTPmn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimetableControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TimetableController' shared autowired service.
     *
     * @return \App\Controller\TimetableController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TimetableController.php';

        $container->services['App\\Controller\\TimetableController'] = $instance = new \App\Controller\TimetableController(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\TimetableRepository'] ?? $container->load('getTimetableRepositoryService')), ($container->privates['App\\Repository\\GroupUserRepository'] ?? $container->load('getGroupUserRepositoryService')), ($container->privates['App\\Repository\\GroupRepository'] ?? $container->load('getGroupRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\TimetableController', $container));

        return $instance;
    }
}
