controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#index:
#    path: /
#    controller: App\Controller\MainController::index
#
#home:
#    path: /home
#    controller: App\Controller\MainController::homeAction