<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6aQTPmn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6aQTPmn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6aQTPmn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6aQTPmn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6aQTPmn\App_KernelDevDebugContainer([
    'container.build_hash' => '6aQTPmn',
    'container.build_id' => 'f4e0d8eb',
    'container.build_time' => 1679395001,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6aQTPmn');
